/* ---- auth ---- */
function authView(m){const s=m=='signup';$('#app').innerHTML=`<div class="form"><a data-a="go" data-to="" class="mu">← Home</a><div class="ban">${banner(s?0:3)}</div><h2>${s?'Create your MANSHORA profile':'Welcome back'}</h2><form id="af" novalidate>${s?'<label>Full name</label><input id="a_n" autocomplete="name">':''}<label>Email</label><input id="a_e" type="email" autocomplete="email"><label>Password</label><input id="a_p" type="password" autocomplete="${s?'new-password':'current-password'}">
${s?`<label>Confirm password</label><input id="a_c" type="password"><div class="row"><div><label>Monthly income (₹)</label><input id="a_i" type="number" min="0"></div><div><label>Monthly expenses (₹, optional)</label><input id="a_x" type="number" min="0"></div><div><label>Employment</label><select id="a_m"><option>Salaried</option><option>Self-employed</option><option>Freelancer</option><option>Student</option></select></div><div><label>Location</label><input id="a_l"></div></div><div class="row"><div><label>Age (optional)</label><input id="a_a" type="number" min="18"></div><div><label>Credit score (optional)</label><input id="a_cs" type="number" min="300" max="900"></div><div><label>Outstanding loans ₹ (optional)</label><input id="a_lb" type="number" min="0"></div><div><label>Digital banking usage 0-100 (optional)</label><input id="a_d" type="number" min="0" max="100"></div></div><label>Financial goals</label><input id="a_g" placeholder="e.g. Buy a home in 5 years">`:''}
<div class="err" id="er"></div><button class="btn" type="submit">${s?'Create account':'Log in'}</button></form><p class="mu">${s?'Have an account?':'New here?'} <a style="color:var(--cy)" data-a="go" data-to="${s?'login':'signup'}">${s?'Log in':'Sign up'}</a></p><p class="disc">Accounts and data are stored only in this browser. ${DISC}</p>${appFoot()}</div>`;
$('#af').onsubmit=async e=>{e.preventDefault();const v=id=>($(id)||{}).value||'',em=v('#a_e').trim().toLowerCase(),pw=v('#a_p'),er=t=>{$('#er').textContent=t};
if(!/^[^@\s]+@[^@\s]+\.[^@\s]+$/.test(em))return er('Enter a valid email address.');
if(!s){const u=users[em];if(!u||u.hash!==await hash(pw,em))return er('Email or password is incorrect.');LS.s('mz_s',em);return location.hash='#/app/dashboard'}
if(!v('#a_n').trim())return er('Full name is required.');if(pw.length<8||!/[A-Z]/.test(pw)||!/\d/.test(pw))return er('Password needs 8+ characters, an uppercase letter and a number.');if(pw!==v('#a_c'))return er('Passwords do not match.');
const inc=+v('#a_i');if(!(inc>0))return er('Monthly income must be greater than 0.');if(!v('#a_l').trim())return er('Location is required.');if(v('#a_cs')&&(+v('#a_cs')<300||+v('#a_cs')>900))return er('Credit score must be between 300 and 900.');if(v('#a_d')&&(+v('#a_d')<0||+v('#a_d')>100))return er('Digital usage must be between 0 and 100.');if(users[em])return er('An account with this email already exists.');
users[em]={name:v('#a_n').trim(),hash:await hash(pw,em),rec:{},prof:{income:inc,expenses:+v('#a_x')||0,employment:v('#a_m'),location:v('#a_l').trim(),goals:v('#a_g'),loan:+v('#a_lb')||0,credit:+v('#a_cs')||0,adopt:+v('#a_d')||0,age:+v('#a_a')||0}};save();LS.s('mz_s',em);toast('Profile created. Add your first month to unlock insights.');location.hash='#/app/months'}}
