/* ---- landing ---- */
const ABOUT=[['Who We Are','An AI-native financial intelligence platform.','MANSHORA turns raw financial data into clear insight for individuals, SMEs and financial institutions.'],['What We Do','Analytics, forecasting and guidance.','Dashboards, simulators, advisors and an AI council work on your month-by-month data.'],['Our Mission','Make financial data simple.','Analyze. Understand. Predict. Act. Every number should lead to a decision.'],['Our Vision','A private intelligence layer over every balance sheet.','Financial clarity for anyone, not just analysts.'],['Why MANSHORA','Finance + AI + Analytics.','Real formulas, transparent rule-based intelligence, and clear visuals in one place.'],['Careers','We are building the team.','Future roles: data science, fintech engineering, product design, risk analytics.']];
const PROD=[['AI Financial Intelligence Platform','Turns financial data into health scores and insights.','Health score, digital twin, AI council'],['Financial Analytics Dashboard','Interactive KPIs, charts and trends.','Net worth, savings rate, income vs expenses'],['AI Financial Assistant','Ask about savings, loans, cars and investing.','Explanation, calculation, action plan'],['Expense & Revenue Analytics','Understand income, spending and profit by month.','Monthly records, timeline, history'],['Financial Forecasting','Project savings, investments and net worth.','Three-scenario simulation lab'],['Automated Financial Reports','Structured summaries from your data.','Council synthesis and manager view']];
const SOL=[['Personal Finance','Unclear spending','Monthly tracking and a health score','Budget and savings targets'],['Startups & SMEs','Cash-flow surprises','Revenue and expense trends','Plan runway and hiring'],['Business Intelligence','Scattered metrics','Unified segment dashboards','Prioritise segments'],['Financial Planning','Goals without numbers','Scenario simulation','Choose a monthly investment'],['Performance Analytics','Slow reporting','Live KPIs and filters','Act on weak areas'],['Risk & Trend Analysis','Hidden debt stress','DTI and credit indicators','Reduce risk early']];
const card=(a,extra,i)=>`<div class="card h" data-a="tg">${art(i)}<h3>${a[0]}</h3><div class="mu">${a[1]}</div><div class="more">${a[2]}${extra||''}</div></div>`;
function landing(){$('#app').innerHTML=`<header class="nav"><div class="logo">MANSHORA<small>Insight Engineered for Impact</small></div><button class="burger" data-a="bg" aria-label="Menu">☰</button><nav id="nv">${['home','about','products','solutions','resources'].map(x=>`<a data-a="sc" data-id="${x}">${x[0].toUpperCase()+x.slice(1)}</a>`).join('')}<a data-a="go" data-to="login">Login</a><button class="btn" data-a="go" data-to="signup">Sign Up</button></nav></header>
<section class="hero" id="home"><div class="hero2"><div><h1>Turn Financial Data Into Intelligent Decisions.</h1><p>MANSHORA combines financial intelligence, artificial intelligence and advanced analytics to help individuals, businesses and financial institutions understand, predict and act on their financial data.</p><p><button class="btn" data-a="sc" data-id="products">Explore Platform</button> <button class="btn g" data-a="go" data-to="signup">Get Started</button></p><div class="pipe"><b>Data</b>›<b>Analytics</b>›<b>AI</b>›<b>Insights</b>›<b>Decisions</b></div></div><div><div id="h3d" class="c3d" data-h="340"></div><p class="mu" style="font-size:12px">Decorative 3D illustration. Drag to rotate.</p></div></div></section>
<section class="sec" id="about"><h2>About MANSHORA</h2><p class="mu">We believe financial data should not be complicated. Tap a card to expand.</p><div class="grid">${ABOUT.map((a,i)=>card(a,'',i)).join('')}</div></section>
<section class="sec" id="products"><h2>Products</h2><div class="grid">${PROD.map((a,i)=>card(a,'<p><button class="btn s" data-a="go" data-to="signup">Get started</button></p>',i+2)).join('')}</div></section>
<section class="sec" id="solutions"><h2>Solutions</h2><div class="grid">${SOL.map((s,i)=>`<div class="card h">${art(i+4)}<h3>${s[0]}</h3><div class="mu"><b>Problem:</b> ${s[1]}<br><b>Intelligence:</b> ${s[2]}<br><b>Action:</b> ${s[3]}</div></div>`).join('')}</div></section>
${footHTML()}`}
