/* ---- app pages ---- */
const NAV=[['dashboard','◧','Dashboard'],['months','▤','Monthly Data'],['twin','◉','Twin & AI Council'],['coach','✦','Financial Coach'],['sim','∿','Simulation Lab'],['loan','₹','Loan Advisor'],['manager','▦','Manager Dashboard']];
const kpi=(l,v,s)=>`<div class="card"><div class="mu">${l}</div><div class="k">${v}</div>${s?`<div class="mu" style="font-size:12px">${s}</div>`:''}</div>`;
const empty=`<div class="card"><h3>No financial data yet</h3><p class="mu">Add your first monthly record to unlock financial health insights.</p><button class="btn" data-a="go" data-to="app/months">Add your first month</button></div>`;
const PG={
dashboard(u){const c=userC(u);if(!c.has)return empty;const k=ms(u),L=k.map(x=>MN[+x.slice(5)-1]),rr=k.map(x=>u.rec[x]);P3=[[{n:'Income',d:rr.map(r=>+r.inc+ +r.oi)},{n:'Expenses',d:rr.map(r=>+r.exp+ +r.oe+ +r.emi)}],L];
return`<div class="grid">${kpi('Financial health score',c.score+'/100',c.score>=70?'Strong':c.score>=50?'Moderate':'Needs attention')}${kpi('Monthly income',R(c.inc))}${kpi('Monthly expenses',R(c.out),'incl. EMI')}${kpi('Monthly savings',R(c.inc-c.out))}${kpi('Savings rate',c.sr.toFixed(1)+'%')}${kpi('Investments',R(c.invT))}${kpi('Outstanding loans',R(c.loan))}${kpi('Net worth',R(c.nw))}${kpi('Digital adoption',c.adopt?c.adopt+'/100':'Not provided')}</div>
<div class="grid" style="margin-top:14px"><div class="card"><h3>Income vs expenses</h3>${chart([{n:'Income',d:rr.map(r=>+r.inc+ +r.oi)},{n:'Expenses',d:rr.map(r=>+r.exp+ +r.oe+ +r.emi)}],L,1)}</div><div class="card"><h3>Savings trend</h3>${chart([{n:'Savings',d:rr.map(r=>+r.sav)},{n:'Investments',d:rr.map(r=>+r.inv)}],L)}</div></div>
<div class="card" style="margin-top:14px"><h3>3D view: income vs expenses</h3><div id="d3" class="c3d"></div><p class="mu" style="font-size:12px">Drag to rotate, hover a bar for its value.</p></div><div class="card" style="margin-top:14px"><h3>Next best action</h3><div id="nba" class="mu">Get a recommendation based on your latest month.</div><p><button class="btn" data-a="nba">Next best action</button></p></div><p class="disc">${DISC}</p>`},
months(u){const k=ms(u),cur=sel&&u.rec[sel]?u.rec[sel]:{},d=new Date(),sk=sel||mkey(d.getFullYear(),d.getMonth()),f=(id,l)=>`<div><label>${l}</label><input id="m_${id}" type="number" min="0" value="${cur[id]??''}"></div>`;
return`<div class="card"><h3>Monthly timeline · <input id="yr" type="number" value="${yr}" style="width:90px;display:inline-block" data-a="yr"></h3><div>${MN.map((m,i)=>{const kk=mkey(yr,i);return`<span class="chip ${u.rec[kk]?'has':''} ${kk==sk?'on':''}" data-a="pick" data-k="${kk}">${m}</span>`}).join('')}</div><p class="mu" style="font-size:12px">Filled months are highlighted. Pick any month to add or edit it, including planned future months.</p></div>
<div class="card" style="margin-top:14px"><h3>${u.rec[sk]?'Edit':'Add'} ${MN[+sk.slice(5)-1]} ${sk.slice(0,4)}</h3><div class="row">${f('inc','Income')}${f('oi','Other income')}${f('exp','Expenses')}${f('oe','Other expenses')}${f('emi','EMI')}${f('sav','Savings')}${f('inv','Investments')}</div><input type="hidden" id="m_k" value="${sk}"><div class="err" id="er"></div><button class="btn" data-a="savem">Save month</button> ${u.rec[sk]?'<button class="btn g" data-a="delm" data-k="'+sk+'">Delete month</button>':''}</div>
<div class="card tw" style="margin-top:14px"><h3>History</h3>${k.length?`<table><tr><th>Month</th><th>Income</th><th>Expenses</th><th>EMI</th><th>Savings</th><th>Invested</th><th></th></tr>${k.map(x=>{const r=u.rec[x];return`<tr><td>${MN[+x.slice(5)-1]} ${x.slice(0,4)}</td><td>${R(+r.inc+ +r.oi)}</td><td>${R(+r.exp+ +r.oe)}</td><td>${R(r.emi)}</td><td>${R(r.sav)}</td><td>${R(r.inv)}</td><td><button class="btn s g" data-a="pick" data-k="${x}">Edit</button></td></tr>`}).join('')}</table>`:'<p class="mu">Your saved months will appear here and stay available every time you return.</p>'}</div>`},
twin(u){const c=userC(u);if(!c.has)return empty;
return`<div class="grid">${kpi('Customer',c.name,c.city+(c.age?' · age '+c.age:''))}${kpi('Income',R(c.inc),'Monthly')}${kpi('Credit score',c.credit||'Not provided')}${kpi('Health score',c.score,c.risk+' risk · '+c.seg)}${kpi('Net worth',R(c.nw))}${kpi('Savings rate',c.sr.toFixed(1)+'%')}${kpi('Digital adoption',c.adopt?c.adopt+'/100':'Not provided')}${kpi('Engagement',c.eng+'/100')}${kpi('Months recorded',ms(u).length)}</div>
<h3 style="margin-top:20px">AI Council <span class="tag">Rule-based intelligence</span></h3><div id="cn"><button class="btn" data-a="cn" data-id="${c.id}">Run AI Council</button></div><p class="disc">${DISC}</p>`},
coach(u){const c=userC(u);if(!c.has)return empty;return`<div class="card"><h3>AI Financial Coach <span class="tag">Rule-based</span></h3><div class="chat" id="ch">${chat.length?chat.map(m=>`<div class="msg ${m.u?'u':''}">${m.t}</div>`).join(''):'<p class="mu">Ask a question or use a quick action. Answers use your latest month.</p>'}</div>
<div>${['Improve savings','Plan investment','Check loan eligibility','Improve credit score','Create budget','Can I afford a ₹10 lakh car?'].map(q=>`<span class="chip" data-a="ask" data-q="${q}">${q}</span>`).join('')}</div><div class="row" style="grid-template-columns:1fr auto;margin-top:8px"><input id="cq" placeholder="How can I save more money?"><button class="btn" data-a="ask">Ask</button></div><p class="disc">Educational information only. Recommendations are not guaranteed financial advice.</p></div>`},
sim(u){const c=userC(u);return`<div class="card" id="sim"><h3>Financial Simulation Lab</h3><p class="mu">Change any value; results update live.</p><div class="row">${[['inc','Monthly income',c.inc],['exp','Monthly expenses',c.exp],['sv','Current savings',c.cash],['ia','Current monthly investment',c.invM||0],['ln','Loan amount',Math.max(c.loan,0)],['rt','Interest rate %',9],['tn','Tenure (years)',5],['fl','Inflation %',5],['rr','Expected return %',11]].map(x=>`<div><label>${x[1]}</label><input id="s_${x[0]}" type="number" min="0" value="${Math.round(x[2])}"></div>`).join('')}</div></div><div id="so" style="margin-top:14px"></div>`},
loan(u){const c=userC(u);return`<div class="card" id="loanf"><h3>AI Loan Advisor <span class="tag">SIMULATED ASSESSMENT</span></h3><div class="row">${[['inc','Monthly income',c.inc],['ee','Existing EMI',c.emi||0],['cs','Credit score',c.credit],['rq','Requested loan',0],['tn','Tenure (years)',20],['rt','Interest rate %',8.5]].map(x=>`<div><label>${x[1]}</label><input id="l_${x[0]}" type="number" min="0" value="${x[2]}"></div>`).join('')}</div></div><div id="lo" style="margin-top:14px"></div>`},
manager(){if(!ALLC().length)return empty;const f=ALLC().filter(c=>(!MG.city||c.city==MG.city)&&(!MG.seg||c.seg==MG.seg)&&(!MG.risk||c.risk==MG.risk)),n=f.length,av=k=>n?f.reduce((a,c)=>a+c[k],0)/n:0,S=['High Value','Growth Opportunity','Digitally Active','At Risk','Low Engagement'],Ci=[...new Set(ALLC().map(c=>c.city))],sel_=(k,o)=>`<select data-a="mf" data-k="${k}"><option value="">All ${k}</option>${o.map(x=>`<option ${MG[k]==x?'selected':''}>${x}</option>`).join('')}</select>`;
return`<div class="grid">${sel_('city',Ci)}${sel_('seg',S)}${sel_('risk',['Low','Medium','High'])}</div>${n?`<div class="grid" style="margin-top:14px">${kpi('Customers',n)}${kpi('Active (engagement ≥ 50)',f.filter(c=>c.eng>=50).length)}${kpi('Digital adoption',av('adopt').toFixed(0)+'/100')}${kpi('Avg health score',av('score').toFixed(0))}${kpi('Loan holders',Math.round(f.filter(c=>c.emi>0).length/n*100)+'%')}${kpi('Investment adoption',Math.round(f.filter(c=>c.invT>0).length/n*100)+'%')}${kpi('High-risk customers',f.filter(c=>c.risk=='High').length)}</div>
<div class="grid" style="margin-top:14px"><div class="card"><h3>Segments</h3>${chart([{n:'Customers',d:S.map(s=>f.filter(c=>c.seg==s).length)}],S.map(s=>s.split(' ')[0]),1)}</div><div class="card"><h3>Digital adoption by city</h3>${chart([{n:'Avg adoption',d:Ci.map(x=>{const g=f.filter(c=>c.city==x);return g.length?g.reduce((a,c)=>a+c.adopt,0)/g.length:0})}],Ci.map(x=>x.slice(0,4)),1)}</div></div>
<div class="card" style="margin-top:14px"><h3>3D view: customers by segment</h3>${(P3=[[{n:'Customers',d:S.map(s=>f.filter(c=>c.seg==s).length)}],S.map(s=>s.split(' ')[0])],'')}<div id="d3" class="c3d"></div></div><div class="card tw" style="margin-top:14px"><h3>Customers</h3><table><tr><th>ID</th><th>Name</th><th>City</th><th>Segment</th><th>Health</th><th>Risk</th></tr>${f.slice(0,10).map(c=>`<tr><td>${c.id}</td><td>${c.name}</td><td>${c.city}</td><td>${c.seg}</td><td>${c.score}</td><td>${c.risk}</td></tr>`).join('')}</table></div>`:'<div class="card"><h3>No customers match</h3><p class="mu">Clear a filter to see customers again.</p><button class="btn" data-a="mfc">Clear filters</button></div>'}<p class="disc">Shows accounts registered in this browser. No messages are sent.</p>`}};
function shell(u,p){if(!PG[p])p='dashboard';P3=null;$('#app').innerHTML=`<div class="shell"><aside class="side ${side?'c':''}"><div class="logo brand" style="padding:6px 10px 12px"><span class="lb">MANSHORA</span></div>${NAV.map(n=>`<a class="${n[0]==p?'on':''}" data-a="go" data-to="app/${n[0]}" title="${n[2]}"><span>${n[1]}</span><span class="lb">${n[2]}</span></a>`).join('')}<a id="col" data-a="col"><span>⇔</span><span class="lb">Collapse</span></a></aside><main class="main"><div class="top"><h2>${NAV.find(n=>n[0]==p)[2]}</h2><div><span class="mu">${u.name}</span> <button class="btn g s" data-a="out">Log out</button></div></div><div class="ban">${banner(NAV.findIndex(n=>n[0]==p))}</div><div id="pg"></div>${appFoot()}</main></div>`;
try{$('#pg').innerHTML=PG[p](u)}catch(e){$('#pg').innerHTML='<div class="card"><h3>Something went wrong</h3><p class="mu">This view could not load.</p><button class="btn" data-a="go" data-to="app/dashboard">Back to dashboard</button></div>'}
if($('#d3')&&P3)bars3d($('#d3'),P3[0],P3[1]);try{ui(u,p)}catch(e){console.error(e)}
({sim:simCalc,loan:loanCalc})[p]&&({sim:simCalc,loan:loanCalc})[p]();const cs=$('#cs');if(cs)cs.onchange=()=>{sel=cs.value;route()}}
