const MAIL='hello@manshora.example',WEBSITE='',LINKEDIN='';
const P_=(...a)=>a.map(x=>`<p>${x}</p>`).join('');
const FT={
insights:['Insights',P_('<b>Three numbers describe most people\'s financial health.</b>','<b>Savings rate</b> is the share of income you keep after spending. Around 20% is a common target.','<b>Debt-to-income</b> is your monthly EMIs divided by income. Keeping it under about 40% leaves room for emergencies.','<b>Emergency fund</b> is savings divided by monthly spending. Three to six months is a common goal.','MANSHORA calculates all three from the months you record and turns them into a score and next steps.')],
blogs:['Blogs',P_('<b>How the 100-point health score works</b><br>35 points come from savings rate (full marks at 30%), 25 from low debt-to-income, 25 from emergency fund (full marks at 6 months) and 15 from investments.','<b>Why monthly records beat yearly summaries</b><br>Month-by-month data shows trends, sudden spikes and income changes that a yearly total hides. That is why MANSHORA keeps every month and only asks you for the new one.')],
reports:['Reports',P_('Two reports are available inside the app:','<b>Banking report (PDF)</b> on the Advisors page: profile, key numbers, health score and next action.','<b>Executive summary</b> on the Executive Intelligence page: customer analytics, predictions and revenue opportunity.','<button class="btn s" data-a="mgo" data-to="app/advisors">Open Advisors</button>')],
cases:['Case Studies',P_('MANSHORA does not publish invented customer stories. Case studies will appear here once real customers or partner institutions agree to share their results.','Until then, try the platform with your own numbers to see how it works.')],
faqs:['FAQs',`<details><summary>Is my data sent to a server?</summary><p>No. In this version everything is saved in your own browser.</p></details><details><summary>Is this financial advice?</summary><p>No. MANSHORA gives educational and simulated insights only.</p></details><details><summary>Is the loan result a bank approval?</summary><p>No. It is a simulated assessment based on EMI and debt-to-income rules.</p></details><details><summary>Are PAN and Aadhaar numbers stored?</summary><p>No. Images are analysed in your browser and numbers are always shown masked.</p></details><details><summary>Why do some screens say Not provided?</summary><p>We never guess. Add the value at signup or in Digital Adoption to see results.</p></details><details><summary>How do I remove my data?</summary><p>Clear this site's data in your browser settings.</p></details>`],
help:['Help Center',P_('<b>Getting started</b>')+'<ol><li>Sign up with your income and location.</li><li>Open Monthly Data and add this month.</li><li>Open Dashboard to see your health score.</li><li>Add digital usage in Digital Adoption.</li><li>Ask the AI Chatbot anything, or open the Planner.</li></ol>'+P_('Need more help? <a style="color:var(--cy)" data-a="ft" data-k="contact">Send us a message</a>.')],
privacy:['Privacy Policy',P_('This version of MANSHORA runs in your browser. The profile and monthly records you enter are saved in your browser\'s local storage on your device. They are not sent to a server.','Passwords are hashed with SHA-256 before saving. Document images are analysed in your browser and never stored; PAN and Aadhaar numbers are displayed masked only.','You can delete your data at any time by clearing this site\'s data in your browser. If a server is added in future, this policy will be updated before any data leaves your device.')],
terms:['Terms &amp; Conditions',P_('MANSHORA is provided for education and demonstration. Outputs are estimates based on the information you enter and on simple rules and models.','You are responsible for the accuracy of what you enter. Do not upload documents that belong to other people.','MANSHORA is not a bank, lender, insurer or investment adviser, and results are not offers or approvals.')],
disclaimer:['Disclaimer',P_(DISC,'Screens marked Simulated or Rule-based use demo rules. Predictions use heuristic models and are not guaranteed.')],
cookies:['Cookie Policy',P_('MANSHORA does not use tracking or advertising cookies.','It uses your browser\'s local storage to remember your account, session, sidebar state and monthly records.','Libraries for 3D charts, PDF reports and text reading are loaded from a public CDN (cdnjs). As with any CDN, it can see your IP address when the library is requested.')],
contact:['Contact us',`<p>Email: <a style="color:var(--cy)" href="mailto:${MAIL}">${MAIL}</a> · India</p><label>Your name</label><input id="ct_n"><label>Your email</label><input id="ct_e" type="email"><label>Message</label><textarea id="ct_m" rows="4"></textarea><div class="err" id="ct_x"></div><button class="btn" data-a="ctsend">Open in my email app</button><p class="disc">This opens your email app with the message ready. Nothing is stored or sent by this page.</p>`]};
const fl=(k,t)=>`<a data-a="ft" data-k="${k}">${t}</a>`;
const footHTML=()=>`<footer id="resources" class="foot"><div><b>MANSHORA</b><span class="mu">Insight Engineered for Impact</span><p class="mu">Finance + AI + Analytics</p></div><div><b>Resources</b>${fl('insights','Insights')}${fl('blogs','Blogs')}${fl('reports','Reports')}${fl('cases','Case Studies')}${fl('faqs','FAQs')}${fl('help','Help Center')}</div><div><b>Contact</b><a href="mailto:${MAIL}">Email</a><span>India</span>${WEBSITE?`<a href="${WEBSITE}" target="_blank" rel="noopener">Website</a>`:''}${LINKEDIN?`<a href="${LINKEDIN}" target="_blank" rel="noopener">LinkedIn</a>`:''}${fl('contact','Send us a message')}</div><div><b>Legal</b>${fl('privacy','Privacy Policy')}${fl('terms','Terms &amp; Conditions')}${fl('disclaimer','Disclaimer')}${fl('cookies','Cookie Policy')}</div><div style="grid-column:1/-1;border-top:1px solid var(--line);padding-top:12px">${DISC}<br>© 2026 MANSHORA. All Rights Reserved. <a data-a="top" style="display:inline;color:var(--cy)">Back to top ↑</a></div></footer>`;
const appFoot=()=>`<div class="afoot">${['privacy:Privacy','terms:Terms','disclaimer:Disclaimer','cookies:Cookies','help:Help','contact:Contact'].map(x=>fl(...x.split(':'))).join(' · ')}<br>© 2026 MANSHORA. Educational and simulated insights only.</div>`;
function modal(k){const m=FT[k];if(!m)return;let o=$('#mdl');if(!o){o=document.createElement('div');o.id='mdl';o.dataset.a='mbg';document.body.append(o)}o.innerHTML=`<div class="mbox" role="dialog" aria-modal="true" aria-label="${m[0]}"><button class="btn g s mx" data-a="mclose" aria-label="Close">✕</button><h2>${m[0]}</h2>${m[1]}</div>`;o.className='on'}
Object.assign(A,{ft:t=>modal(t.dataset.k),mclose:()=>{const o=$('#mdl');if(o)o.className=''},mbg:(t,e)=>{if(e.target===t)A.mclose()},mgo:t=>{A.mclose();A.go(t)},top:()=>window.scrollTo({top:0,behavior:'smooth'}),
ctsend:()=>{const n=S('#ct_n').trim(),e=S('#ct_e').trim(),m=S('#ct_m').trim(),x=$('#ct_x');if(!n||!m)return x.textContent='Please enter your name and a message.';if(!/^[^@\s]+@[^@\s]+\.[^@\s]+$/.test(e))return x.textContent='Enter a valid email address.';x.textContent='';location.href='mailto:'+MAIL+'?subject='+encodeURIComponent('MANSHORA enquiry from '+n)+'&body='+encodeURIComponent(m+'\n\nReply to: '+e)}});
document.addEventListener('keydown',e=>{if(e.key=='Escape')A.mclose()});addEventListener('hashchange',()=>A.mclose());
