const X=u=>u.prof.x=u.prof.x||{},V=id=>+(($(id)||{}).value)||0,S=id=>($(id)||{}).value||'',CD=(t,b)=>`<div class="card" style="margin-top:14px"><h3>${t}</h3>${b}</div>`,GR=a=>`<div class="grid">${a.join('')}</div>`,LI=a=>'<ul style="margin:6px 0;padding-left:18px">'+a.map(x=>`<li>${x}</li>`).join('')+'</ul>',FL=(id,l,v)=>`<div><label>${l}</label><input id="${id}" type="number" min="0" value="${v??''}"></div>`,YN=(id,l,v)=>`<div><label>${l}</label><select id="${id}"><option value="0">No</option><option value="1" ${v?'selected':''}>Yes</option></select></div>`,avg=a=>a.length?a.reduce((x,y)=>x+y,0)/a.length:0,sig=z=>1/(1+Math.exp(-z)),pb=v=>`<div class="pb"><i style="width:${cl(v,0,100)}%"></i></div>`,pc=x=>Math.round(x*100),TB=(h,r)=>r.length?`<div class="tw"><table><tr>${h.map(x=>`<th>${x}</th>`).join('')}</tr>${r.map(x=>`<tr>${x.map(y=>`<td>${y}</td>`).join('')}</tr>`).join('')}</table></div>`:'<p class="mu">None found.</p>';
let hs='',hqv='',pl='sip',lg='en-IN',SPK=false;const WA=[],POST={};
/* ML */
const lin=y=>{const n=y.length,xm=(n-1)/2,ym=avg(y);let a=0,b=0;y.forEach((v,i)=>{a+=(i-xm)*(v-ym);b+=(i-xm)**2});const s=b?a/b:0;return{s,f:k=>ym+s*(n-1+k-xm)}};
const km=(P,k)=>{k=Math.min(k,P.length);let C=[...Array(k).keys()].map(i=>P[Math.floor(i*(P.length-1)/Math.max(k-1,1))].slice()),L=[];for(let t=0;t<15;t++){L=P.map(p=>{let bi=0,bd=1e9;C.forEach((c,i)=>{const d=p.reduce((a,v,j)=>a+(v-c[j])**2,0);if(d<bd){bd=d;bi=i}});return bi});C=C.map((c,i)=>{const m=P.filter((_,j)=>L[j]==i);return m.length?c.map((_,d)=>avg(m.map(p=>p[d]))):c})}return{L,C}};
/* domain */
function dscore(u){const d=X(u).dg;return d?Math.round(Math.min(30,d.upi)+Math.min(25,d.mob/20*25)+Math.min(10,d.net/4*10)+(d.inv?15:0)+(d.ln?10:0)+(d.sup?10:0)):0}
const dgaps=c=>{const d=X(c.u).dg;if(!d)return['Digital usage not entered yet'];const g=[];d.upi<15&&g.push(`UPI use is ${d.upi}/month (target 15+)`);d.mob<10&&g.push(`Mobile banking logins ${d.mob}/month (target 10+)`);d.net<2&&g.push('Internet banking rarely used');!d.inv&&g.push('No online investing');!d.ln&&g.push('No online loan usage');!d.sup&&g.push('Online support unused');return g};
const spendCV=u=>{const e=ms(u).map(k=>+u.rec[k].exp+ +u.rec[k].oe),m=avg(e);return{e,m,sd:Math.sqrt(avg(e.map(x=>(x-m)**2)))}};
const flags=u=>{const s=spendCV(u),k=ms(u);return s.e.length>=5?k.filter((_,i)=>s.sd&&(s.e[i]-s.m)/s.sd>1.8):[]};
const wellness=c=>Math.round(c.score*.6+cl(c.ins/(c.inc*120||1),0,1)*15+cl(c.em/6,0,1)*10+(c.credit?cl((c.credit-300)/600,0,1)*15:7));
const riskApp=c=>{const s=50+(c.age?(40-c.age)*.8:0)+cl(c.invT/(c.inc*12||1),0,1)*30-c.dti*.4-(c.em<3?10:0);return{s:Math.round(cl(s,0,100)),l:s<40?'Conservative':s<65?'Moderate':'Aggressive'}};
const prods=c=>{const p=[];c.invM<c.inc*.1&&c.inc>c.out&&p.push('SIP / mutual fund');c.ins<c.inc*120&&p.push('Term life insurance');c.em<3&&p.push('Recurring deposit for emergency fund');c.adopt&&c.adopt<50&&p.push('UPI and mobile banking onboarding');c.dti<30&&c.score>65&&p.push('Pre-approved loan review');c.credit>=750&&p.push('Premium credit card');return p};
const life=u=>{const c=userC(u),k=ms(u),inc=k.map(x=>+u.rec[x].inc+ +u.rec[x].oi),g=(u.prof.goals||'').toLowerCase(),h=r=>r.test(g),L=inc.length,pv=avg(inc.slice(0,-1)),j=L>1&&pv?(inc[L-1]-pv)/pv:0,sg=L>1?`Latest income ${(j*100).toFixed(0)}% vs earlier average`:'Needs 2+ months of records';
return[{e:'Salary hike',p:j>=.08?Math.min(95,Math.round(60+j*200)):0,sig:sg,pr:'SIP top-up, goal plan'},{e:'New job / income change',p:Math.abs(j)>=.15?70:0,sig:sg,pr:'Salary account, insurance review'},{e:'Marriage',p:h(/marri|wedding|shaadi/)?(c.age>=24&&c.age<=32?80:65):0,sig:'Stated goal',pr:'Joint planning, term insurance'},{e:'Home purchase',p:h(/home|house|flat|apartment/)?Math.min(90,Math.round(55+Math.max(0,c.sr))):0,sig:'Stated goal and savings rate',pr:'Home loan, home insurance, savings plan'},{e:'Travel',p:h(/travel|trip|vacation|holiday/)?65:0,sig:'Stated goal',pr:'Forex card, travel insurance'},{e:'Education planning',p:h(/educat|study|mba|college|school|child|masters/)?70:0,sig:'Stated goal',pr:'Education loan, child plan'},{e:'Retirement readiness',k:'ready',p:c.age?pc(cl((c.cash+c.invT)/(c.out*12*25||1),0,1)):null,sig:c.age?'Corpus vs 25x annual spend':'Add age at signup',pr:'NPS, long-term SIP'}]};
const agents2=c=>{const e=life(c.u).filter(x=>x.p&&x.k!='ready'),fl=flags(c.u),ps=prods(c),w=wellness(c),o=council(c),cv=spendCV(c.u),v=cv.m?cv.sd/cv.m:0,tg=c.inc*120;return[...agents(c),
['Behavior Agent',v>.2?'warn':'ok',v>.2?'Spending is volatile month to month.':'Spending is stable.',75,`Variation ${(v*100).toFixed(0)}% over ${cv.e.length} months.`],
['Insurance Agent',c.ins>=tg?'ok':'warn',c.ins>=tg?'Cover looks adequate.':`Consider cover near ${R(tg)} (10x annual income).`,70,`Current cover ${R(c.ins)}.`],
['Fraud Agent',fl.length?'bad':'ok',fl.length?`Unusual spend in ${fl.join(', ')}. Verify transactions.`:'No spending anomalies found.',cv.e.length>=5?78:50,cv.e.length>=5?'Flags months above 1.8 standard deviations.':'Needs 5+ months for reliable detection.'],
['Life Event Agent',e.length?'ok':'warn',e.length?'Likely: '+e.map(x=>x.e).join(', ')+'.':'No life-event signals detected.',65,'Uses goals and income changes.'],
['Wellness Agent',w>=65?'ok':'warn',`Wellness index ${w}/100.`,80,'Blends health, cover, emergency fund and credit.'],
['Recommendation Agent','ok',ps[0]||'Keep the current plan.',72,'Highest-priority product gap.'],['Next Best Action Agent','ok',o.n,74,'From council synthesis.'],['Product Recommendation Agent','ok',ps.slice(0,3).join(' · ')||'No gaps found.',70,'Matches gaps to products.']]};
const propens=c=>[['SIP',sig(-1.6+3*Math.max(0,(c.inc-c.out)/c.inc)+1.2*c.adopt/100-(c.invM>0?1.5:0)+(c.em>=3?.6:-.4))],['Insurance',sig(-1.2+(c.ins<c.inc*120?1.4:-1)+(c.age>28?.5:0)+(c.loan>0?.5:0))],['Credit card',sig(-1+c.adopt/60+(c.credit>=700?1:-.5))],['Loan',sig(-1.5+(c.dti<30?.8:-.8)+(c.credit>=700?.8:0))]];
const NOTE='<p class="disc">Propensity scores use a heuristic model with fixed weights, not one trained on outcomes.</p>';
/* nav + pages */
NAV.push(['hub','◎','Customer Hub'],['digital','⌁','Digital Adoption'],['life','◈','Life Events'],['plan','∑','Planner & SIP'],['learn','✎','Learning Academy'],['engage','★','Missions & Rewards'],['tools','⚑','Scam & Sentiment'],['camera','◐','Camera Banking'],['advisors','◆','Advisors & Report'],['exec','▣','Executive Intelligence']);
const M0=PG.manager;
PG.manager=u=>{const b=M0(u),A_=ALLC();if(!A_.length)return b;const cities=[...new Set(A_.map(c=>c.city))],ad=x=>{const g=A_.filter(c=>c.city==x&&c.adopt);return g.length?avg(g.map(c=>c.adopt)):0},camp=LS.g('mz_camp',[]),row=c=>[c.id,c.name,c.city,R(c.inc)];
return b+CD('Branch (city) adoption heatmap',`<div class="grid">${cities.map(x=>`<div class="card" style="background:rgba(34,211,238,${.08+ad(x)/140})"><b>${x}</b><div class="k">${Math.round(ad(x))}</div><div class="mu" style="font-size:12px">avg adoption</div></div>`).join('')}</div><div id="d4" class="c3d"></div>`)+CD('Low adoption customer finder',TB(['ID','Name','City','Income'],A_.filter(c=>c.adopt&&c.adopt<40).map(row)))+CD('High value customer finder',TB(['ID','Name','City','Income'],A_.filter(c=>c.inc>=100000||c.nw>1e6).map(row)))+CD('Investment opportunity',TB(['ID','Name','Suggested SIP'],A_.filter(c=>c.invM<c.inc*.1&&c.inc>c.out).map(c=>[c.id,c.name,R(Math.min(c.inc-c.out,c.inc*.1)-c.invM)])))+CD('Insurance opportunity',TB(['ID','Name','Cover gap'],A_.filter(c=>c.ins<c.inc*120).map(c=>[c.id,c.name,R(c.inc*120-c.ins)])))+CD('Fraud monitoring',TB(['ID','Name','Flagged months'],A_.filter(c=>flags(c.u).length).map(c=>[c.id,c.name,flags(c.u).join(', ')])))+CD('Campaign effectiveness',`<div class="row">${'<div><label>Campaign name</label><input id="cp_n"></div>'}<div><label>Channel</label><select id="cp_c"><option>Mobile notification</option><option>Email</option><option>SMS</option><option>WhatsApp</option></select></div>${FL('cp_s','Reached',0)}${FL('cp_v','Converted',0)}</div><button class="btn" data-a="camp">Log campaign</button>${TB(['Campaign','Channel','Reached','Converted','Rate'],camp.map(c=>[c.n,c.c,c.s,c.v,c.s?pc(c.v/c.s)+'%':'-']))}<p class="disc">Enter real results; nothing is sent from this app.</p>`)};
POST.manager=()=>{const A_=ALLC(),ci=[...new Set(A_.map(c=>c.city))];bars3d($('#d4'),[{n:'Avg adoption',d:ci.map(x=>{const g=A_.filter(c=>c.city==x&&c.adopt);return g.length?avg(g.map(c=>c.adopt)):0})}],ci)};
PG.hub=u=>{const A_=ALLC(),m=userC(u);if(!m.has)return empty;const c=hs&&hs!='me'?A_.find(x=>x.id==hs)||m:m,res=hqv?A_.filter(x=>(x.name+x.id+x.city).toLowerCase().includes(hqv.toLowerCase())):[],dna=[['Saver',c.sr/30],['Investor',c.invM/(c.inc*.2||1)],['Borrower',c.dti/50],['Digital',c.adopt/100],['Protector',c.ins/(c.inc*120||1)],['Planner',ms(c.u).length/12]].map(x=>[x[0],pc(cl(x[1],0,1))]),ra=riskApp(c),g=dgaps(c);P3=[[{n:'Financial DNA',d:dna.map(x=>x[1])}],dna.map(x=>x[0])];
return`<div class="card"><label>Customer selection and search (accounts registered in this browser)</label><div class="row" style="grid-template-columns:1fr auto"><input id="hq" value="${hqv}" placeholder="Name, ID or city"><button class="btn" data-a="hs">Search</button></div>${res.length?res.map(x=>`<span class="chip" data-a="hsel" data-id="${x.id}">${x.name} · ${x.id}</span>`).join(''):hqv?'<p class="mu">No registered customer matches.</p>':'<span class="chip" data-a="hsel" data-id="me">My profile</span>'}</div>`+GR([kpi('Customer',c.name,c.city+(c.age?' · age '+c.age:'')),kpi('Income',R(c.inc)),kpi('Health score',c.score+'/100',c.risk+' risk'),kpi('Risk appetite',ra.l,'score '+ra.s+(c.age?'':' · add age for accuracy')),kpi('Digital adoption score',c.adopt?c.adopt+'/100':'Not provided'),kpi('Wellness index',wellness(c)+'/100')])+CD('Financial DNA (3D)','<div id="d3" class="c3d"></div><p class="mu" style="font-size:12px">Saver, Investor, Borrower, Digital, Protector, Planner traits from your data. Drag to rotate.</p>')+CD('Adoption gap detection',LI(g))};
A.hs=()=>{hqv=S('#hq');route()};A.hsel=t=>{hs=t.dataset.id;hqv='';route()};
PG.digital=u=>{const c=userC(u),x=X(u),d=x.dg||{upi:0,mob:0,net:0,inv:0,ln:0,sup:0},form=CD('Digital and insurance profile',`<div class="row">${FL('dg_upi','UPI transactions per month',d.upi)}${FL('dg_mob','Mobile banking logins per month',d.mob)}${FL('dg_net','Internet banking logins per month',d.net)}${YN('dg_inv','Online investing',d.inv)}${YN('dg_ln','Online loans',d.ln)}${YN('dg_sup','Online support',d.sup)}${FL('dg_ins','Insurance cover (₹)',x.ins||0)}</div><button class="btn" data-a="dgsave">Save profile</button>`);if(!x.dg)return'<p class="mu">Enter your usage to compute your digital adoption score. Nothing is assumed.</p>'+form;
const s=c.adopt,g=dgaps(c),P=[['UPI',d.upi/30],['Mobile',d.mob/20],['NetBank',d.net/4],['Invest',d.inv],['Loans',d.ln],['Support',d.sup]].map(a=>[a[0],pc(cl(a[1],0,1))]);P3=[[{n:'Adoption components %',d:P.map(a=>a[1])}],P.map(a=>a[0])];const nm=u.name.split(' ')[0],pr=propens(c);
return GR([kpi('Digital adoption score',s+'/100',s<40?'Low':s<70?'Medium':'High'),kpi('UPI',d.upi+'/month'),kpi('Mobile logins',d.mob+'/month')])+CD('Components (3D)','<div id="d3" class="c3d"></div>')+(x.dh&&x.dh.length>1?CD('History',chart([{n:'Score',d:x.dh.map(h=>h.s)}],x.dh.map(h=>h.d))):'')+CD('Adoption gaps',LI(g))+CD('30-day digital adoption plan',LI([['Week 1',d.upi<15?`Raise UPI use from ${d.upi} to 15+ a month: pay 4 bills by UPI.`:'Keep UPI use steady.'],['Week 2',d.mob<10?`Open the mobile app 3 times a week (now ${d.mob} a month).`:'Try one unused app feature.'],['Week 3',d.inv?'Review your SIP amount.':'Start a small online SIP.'],['Week 4',!d.sup||!d.ln?'Try online support and online loan tools.':'Turn on transaction alerts.']].map(w=>`<b>${w[0]}:</b> ${w[1]}`)))+CD('AI nudge generator',LI([`${nm}, you save ${c.sr.toFixed(0)}% of income. A ${R(c.inc*.05)} monthly SIP can put your surplus to work.`,d.upi<15?`${nm}, paying two more bills by UPI this week builds a habit.`:`${nm}, great UPI activity. Explore online investing next.`,c.ins<c.inc*120?`${nm}, your insurance cover is ${R(c.ins)}. A protection review may help.`:`${nm}, your cover looks healthy. Review nominees yearly.`]))+CD('Future product adoption prediction',pr.map(p=>`<div>${p[0]} · ${pc(p[1])}%${pb(pc(p[1]))}</div>`).join('')+NOTE)};
A.dgsave=()=>{const u=me(),x=X(u);x.dg={upi:V('#dg_upi'),mob:V('#dg_mob'),net:V('#dg_net'),inv:+S('#dg_inv'),ln:+S('#dg_ln'),sup:+S('#dg_sup')};x.ins=V('#dg_ins');x.dh=(x.dh||[]).concat({d:new Date().toLocaleDateString('en-IN',{day:'2-digit',month:'short'}),s:dscore(u)}).slice(-12);save();toast('Digital profile saved');route()};
PG.life=u=>{const c=userC(u);if(!c.has)return empty;return CD('Life event intelligence',TB(['Event','Status','Signal','Relevant products'],life(u).map(e=>[e.e,e.p==null?'-':e.k?e.p+'% ready':e.p?e.p+'% likely':'Not detected',e.sig,e.pr]))+'<p class="disc">Signals come from your goals text, your age and income changes across months. They are estimates, not certainties.</p>')};
const PLAN={sip:['SIP Calculator',c=>[['m','Monthly SIP (₹)',Math.round(c.invM)],['r','Expected return %',12],['y','Years',10]],v=>{const i=v.r/1200,s=[],t=[];for(let y=0;y<=v.y;y++){const m=y*12;s.push(v.m*(i?((1+i)**m-1)/i:m));t.push(v.m*m)}return{h:GR([kpi('Future value',R(s[v.y])),kpi('Invested',R(t[v.y])),kpi('Estimated gains',R(s[v.y]-t[v.y]))]),ser:[{n:'Invested',d:t},{n:'Value',d:s}],lab:s.map((_,y)=>'Y'+y)}}],
wealth:['Wealth Forecast',()=>[],(v,c)=>{const u=me(),y=ms(u).map(k=>+u.rec[k].sav+ +u.rec[k].inv);if(y.length<3)return{h:'<p class="mu">Add at least 3 months of records to forecast.</p>'};const m=lin(y),f=[1,2,3,4,5,6].map(k=>Math.max(0,m.f(k)));return{h:GR([kpi('Trend per month',R(m.s),'linear regression'),kpi('Next 6 months (est.)',R(f.reduce((a,b)=>a+b,0)))]),ser:[{n:'Actual',d:[...y,...f.map(()=>0)]},{n:'Forecast',d:[...y.map(()=>0),...f]}],lab:[...y.map((_,i)=>'M'+(i+1)),...f.map((_,i)=>'F'+(i+1))]}}],
goal:['Goal Planning',c=>[['t','Goal amount (₹)',0],['y','Years',5],['cur','Current savings (₹)',Math.round(c.cash)],['r','Return %',12]],v=>{const n=v.y*12,i=v.r/1200,need=Math.max(0,v.t-v.cur*(1+i)**n),p=n?(i?need*i/((1+i)**n-1):need/n):0;return{h:GR([kpi('Monthly investment needed',R(p)),kpi('Goal',R(v.t)),kpi('Grows from savings',R(v.cur*(1+i)**n))])}}],
retire:['Retirement Simulator',c=>[['a','Current age',c.age],['ra','Retirement age',60],['e','Monthly spend today (₹)',Math.round(c.out)],['inf','Inflation %',6],['r','Return %',10],['cur','Current corpus (₹)',Math.round(c.cash+c.invT)]],v=>{const y=v.ra-v.a;if(!(v.a>0&&y>0))return{h:'<p class="mu">Enter a current age below your retirement age.</p>'};const n=y*12,i=v.r/1200,co=v.e*12*(1+v.inf/100)**y*25,gap=Math.max(0,co-v.cur*(1+i)**n),p=i?gap*i/((1+i)**n-1):gap/n;return{h:GR([kpi('Corpus needed',R(co),'25x future annual spend'),kpi('Monthly SIP needed',R(p)),kpi('Years to retire',y)])}}],
emerg:['Emergency Fund',c=>[['tm','Target months of expenses',6]],(v,c)=>{const need=v.tm*c.out,gap=Math.max(0,need-c.cash),sur=Math.max(0,c.inc-c.out);return{h:GR([kpi('Target fund',R(need)),kpi('Current cover',c.em.toFixed(1)+' months'),kpi('Gap',R(gap),sur?Math.ceil(gap/sur)+' months at current surplus':'No surplus to fill it')])}}],
hike:['Salary Hike Simulator',c=>[['hk','Hike %',10]],(v,c)=>{const ni=c.inc*(1+v.hk/100),ex=ni-c.inc;return{h:GR([kpi('New income',R(ni)),kpi('Extra monthly',R(ex)),kpi('Savings rate after',sr(ni,c.out).toFixed(1)+'%'),kpi('Suggested extra SIP',R(ex*.5),'50% of the hike')])}}]};
PG.plan=u=>{const c=userC(u);return`<div>${Object.keys(PLAN).map(k=>`<span class="chip ${k==pl?'on':''}" data-a="ptab" data-k="${k}">${PLAN[k][0]}</span>`).join('')}</div><div class="card" id="plf" style="margin-top:10px"><div class="row">${PLAN[pl][1](c).map(f=>FL('p_'+f[0],f[1],f[2])).join('')}</div></div><div id="pr" style="margin-top:14px"></div>`};
function planRun(){const c=userC(me()),P=PLAN[pl],v={};P[1](c).forEach(f=>v[f[0]]=V('#p_'+f[0]));const o=P[2](v,c);$('#pr').innerHTML=o.h+(o.ser?CD('3D projection','<div id="d3" class="c3d"></div>')+CD('Chart',chart(o.ser,o.lab)):'')+`<p class="disc">${DISC}</p>`;clearTimeout(t3);if(o.ser)t3=setTimeout(()=>bars3d($('#d3'),o.ser,o.lab),200)}
POST.plan=planRun;A.ptab=t=>{pl=t.dataset.k;route()};document.addEventListener('input',e=>{if(e.target.closest('#plf'))planRun()});
/* voice, avatar, chatbot */
const TR={'hi-IN':{Explanation:'स्पष्टीकरण',Calculation:'गणना',Recommendation:'सुझाव','Action plan':'कार्य योजना'},'ta-IN':{Explanation:'விளக்கம்',Calculation:'கணக்கீடு',Recommendation:'பரிந்துரை','Action plan':'செயல் திட்டம்'}},tx=h=>{const m=TR[lg];return m?h.replace(/<b>(Explanation|Calculation|Recommendation|Action plan)<\/b>/g,(a,k)=>`<b>${m[k]}</b>`):h};
function speak(t){if(!window.speechSynthesis)return toast('Speech is not supported in this browser','bad');speechSynthesis.cancel();const u=new SpeechSynthesisUtterance(t);u.lang=lg;u.onstart=()=>SPK=true;u.onend=u.onerror=()=>SPK=false;speechSynthesis.speak(u)}
function avatar3d(el){if(!el)return;if(!window.THREE){el.innerHTML='<p class="mu">The 3D avatar needs an internet connection for its library.</p>';return}try{const w=el.clientWidth||300,h=240;el.innerHTML='';const sc=new THREE.Scene(),cam=new THREE.PerspectiveCamera(40,w/h,.1,50),rd=new THREE.WebGLRenderer({antialias:true,alpha:true}),M=c=>new THREE.MeshStandardMaterial({color:c,roughness:.5}),g=new THREE.Group(),eye=x=>{const m=new THREE.Mesh(new THREE.SphereGeometry(.18,16,16),M(0xffffff));m.position.set(x,.35,1.35);return m},mo=new THREE.Mesh(new THREE.BoxGeometry(.8,.12,.1),M(0x0a1120));mo.position.set(0,-.55,1.45);rd.setSize(w,h);cam.position.z=6;el.append(rd.domElement);sc.add(new THREE.AmbientLight(0xffffff,.7));const dl=new THREE.DirectionalLight(0xffffff,.8);dl.position.set(3,4,5);sc.add(dl);g.add(new THREE.Mesh(new THREE.SphereGeometry(1.5,32,32),M(0x3b82f6)),eye(-.5),eye(.5),mo);sc.add(g);let mx=0,t=0;el.onpointermove=e=>{const b=el.getBoundingClientRect();mx=((e.clientX-b.left)/b.width-.5)*.9};(function loop(){if(!document.body.contains(rd.domElement)){rd.dispose();return}t+=.2;g.rotation.y+=(mx-g.rotation.y)*.08;mo.scale.y=SPK?1+Math.abs(Math.sin(t*2))*4:1;rd.render(sc,cam);requestAnimationFrame(loop)})()}catch(e){el.innerHTML='<p class="mu">3D avatar is not supported in this browser.</p>'}}
const NV={dashboard:'dashboard',month:'months',twin:'twin',council:'twin',coach:'coach',simul:'sim',loan:'loan',manager:'manager',hub:'hub',digital:'digital',life:'life',plan:'plan',sip:'plan',learn:'learn',scam:'tools',sentiment:'tools',camera:'camera',report:'advisors',portfolio:'advisors',credit:'advisors',mission:'engage',reward:'engage',executive:'exec'};
function bot(q){const c=userC(me()),l=q.toLowerCase(),k=/(open|go to|show me|take me)/.test(l)&&Object.keys(NV).find(x=>l.includes(x));if(k){location.hash='#/app/'+NV[k];return`Opening ${NV[k]}.`}
if(/health score/.test(l))return`Your financial health score is ${c.score}/100 (${c.risk} risk).`;if(/savings rate/.test(l))return`Your savings rate is ${c.sr.toFixed(1)}%.`;if(/net worth/.test(l))return`Your net worth is ${R(c.nw)}.`;if(/adoption/.test(l))return c.adopt?`Your digital adoption score is ${c.adopt}/100.`:'Enter your usage in Digital Adoption to get a score.';if(/otp|scam|fraud/.test(l))return'Never share your OTP, PIN or CVV. Use Scam & Sentiment to check a suspicious message.';return tx(reply(q,c))}
function bRender(){const m=$('#bm');if(!m)return;m.innerHTML=chat.length?chat.map(x=>`<div class="msg ${x.u?'u':''}">${x.t}</div>`).join(''):'<p class="mu">Ask about savings, loans, cars, investing or say "open planner".</p>';m.scrollTop=m.scrollHeight}
A.botT=()=>{const p=$('#bp');p.style.display=p.style.display=='none'?'block':'none';bRender()};
A.bsend=()=>{const q=S('#bq').trim();if(!q)return;$('#bq').value='';chat.push({u:1,t:q});const r=bot(q);chat.push({t:r});bRender();if($('#spk')&&$('#spk').checked)speak(r.replace(/<[^>]+>/g,' '))};
A.mic=()=>{const R_=window.SpeechRecognition||window.webkitSpeechRecognition;if(!R_)return toast('Voice input is not supported in this browser','bad');const r=new R_();r.lang=lg;r.onresult=e=>{$('#bq').value=e.results[0][0].transcript;A.bsend()};r.onerror=()=>toast('Could not hear you','bad');r.start()};
document.addEventListener('change',e=>{if(e.target.id=='lg')lg=e.target.value});document.addEventListener('keydown',e=>{if(e.key=='Enter'&&e.target.id=='bq')A.bsend()});
function ui(u,p){let b=$('#bot');if(!b){b=document.createElement('div');b.id='bot';b.innerHTML='<div id="bp" class="card" style="display:none"><div class="chat" id="bm"></div><div class="row" style="grid-template-columns:1fr auto auto;gap:6px"><input id="bq" placeholder="Ask MANSHORA"><button class="btn s g" data-a="mic">Mic</button><button class="btn s" data-a="bsend">Send</button></div><div class="row" style="margin-top:6px"><select id="lg"><option value="en-IN">English</option><option value="hi-IN">हिन्दी</option><option value="ta-IN">தமிழ்</option></select><label><input type="checkbox" id="spk" style="width:auto"> Speak replies</label></div><p class="disc">Local rule-based assistant. Educational only.</p></div><button class="btn" data-a="botT">AI Chatbot</button>';document.body.append(b)}b.style.display='flex';bRender();POST[p]&&POST[p](u)}
/* learning */
const LES=[['Budgeting basics','Split income roughly 50% needs, 30% wants, 20% savings and track it monthly.',c=>Math.max(0,20-c.sr)],['Emergency fund','Keep 3 to 6 months of expenses in an easy-to-access account before investing.',c=>Math.max(0,3-c.em)*10],['Managing debt','Keep total EMIs under about 40% of income and clear costly debt first.',c=>Math.max(0,c.dti-25)],['SIP and compounding','A regular SIP grows through compounding; starting early matters more than the amount.',c=>c.invM<c.inc*.1?20:0],['Insurance basics','Term cover of about 10 times annual income protects dependants at low cost.',c=>c.ins<c.inc*120?20:0],['Credit score','Pay on time, keep utilisation under 30% and avoid many new credit inquiries.',c=>c.credit&&c.credit<700?20:c.credit?0:8],['Digital safety','Never share OTP or PIN; verify links; use UPI only with known payees.',c=>c.adopt&&c.adopt<50?10:3]];
PG.learn=u=>{const c=userC(u);if(!c.has)return empty;const L=LES.map((l,i)=>({i,l,w:l[2](c)})).sort((a,b)=>b.w-a.w),dn=X(u).learned||[];return`<div class="grid"><div class="card"><h3>AI banking avatar</h3><div id="av" class="c3d" style="height:240px;cursor:default"></div><p class="mu" style="font-size:12px">Move your mouse over it. It speaks lessons aloud (choose language in the chatbot).</p></div><div class="card"><h3>Personalized Learning Academy</h3><p class="mu">Ordered by your biggest gaps.</p>${L.map((o,j)=>`<div style="margin:10px 0"><b>${o.l[0]}</b> ${j<3&&o.w>0?'<span class="tag">Recommended</span>':''}${dn.includes(o.i)?' <span class="tag ok">Learned</span>':''}<div class="mu">${o.l[1]}</div><button class="btn s g" data-a="say" data-i="${o.i}">Read aloud</button> <button class="btn s g" data-a="lrn" data-i="${o.i}">Mark learned</button></div>`).join('')}</div></div>`};
POST.learn=()=>avatar3d($('#av'));A.say=t=>speak(LES[t.dataset.i][0]+'. '+LES[t.dataset.i][1]);A.lrn=t=>{const x=X(me());x.learned=[...new Set([...(x.learned||[]),+t.dataset.i])];save();toast('Lesson marked as learned');route()};
/* engagement */
const today=()=>new Date().toISOString().slice(0,10),MIS=[['log','Record this month in Monthly Data'],['upi','Make one UPI payment'],['learn','Read one lesson in the Academy'],['score','Review your health score'],['scam','Check one message in Scam & Sentiment']];
const badges=c=>{const x=X(c.u),k=ms(c.u);return[['First month recorded',k.length>=1],['3 months recorded',k.length>=3],['Savings rate 20%+',c.sr>=20],['Emergency fund 3+ months',c.em>=3],['Started investing',c.invT>0],['Digital profile complete',!!x.dg],['3 lessons learned',(x.learned||[]).length>=3]]};
PG.engage=u=>{const c=userC(u);if(!c.has)return empty;const x=X(u),m=x.mis||{},dn=m[today()]||[],nowK=mkey(new Date().getFullYear(),new Date().getMonth()),done=id=>id=='log'?!!u.rec[nowK]:dn.includes(id),bd=badges(c),mp=Object.values(m).reduce((a,d)=>a+d.length,0),pts=mp*10+bd.filter(b=>b[1]).length*50,n=ALLC(),rank=n.length>1?pc(n.filter(a=>a.score<=c.score).length/n.length):null;
return GR([kpi('Reward points',pts,'10 per mission · 50 per achievement'),kpi('Achievements',bd.filter(b=>b[1]).length+'/'+bd.length),kpi('Community benchmark',rank==null?'Needs 2+ accounts':'Top '+(101-rank)+'%','health score vs accounts in this browser')])+CD('Daily financial missions',MIS.map(a=>`<label style="display:flex;gap:8px;align-items:center;font-size:14px;color:var(--tx);margin:6px 0"><input type="checkbox" style="width:auto" data-a="mis" data-id="${a[0]}" ${done(a[0])?'checked':''} ${a[0]=='log'?'disabled':''}> ${a[1]}</label>`).join(''))+CD('Achievement system',TB(['Achievement','Status'],bd.map(b=>[b[0],b[1]?'<span class="tag ok">Unlocked</span>':'Locked'])))+CD('WhatsApp AI Coach (preview only)',`<div class="chat" id="wam">${WA.map(x=>`<div class="msg ${x.u?'u':''}">${x.t}</div>`).join('')||'<p class="mu">Try: How can I save more money?</p>'}</div><div class="row" style="grid-template-columns:1fr auto"><input id="wq" placeholder="Message"><button class="btn" data-a="wasend">Send</button></div><p class="disc">Preview only. Nothing is sent to WhatsApp.</p>`)};
A.mis=t=>{const x=X(me());x.mis=x.mis||{};const a=x.mis[today()]||[],id=t.dataset.id;x.mis[today()]=t.checked?[...new Set([...a,id])]:a.filter(y=>y!=id);save();route()};
A.wasend=()=>{const q=S('#wq').trim();if(!q)return;WA.push({u:1,t:q},{t:reply(q,userC(me()))});route()};
/* tools: scam, sentiment */
const SC=[[/otp|\bpin\b|cvv|password|passcode/i,35,'Asks for OTP, PIN, CVV or password'],[/urgent|immediately|within \d+ ?(hours?|mins?)|last chance|act now/i,20,'Creates urgency'],[/blocked|suspend|deactivat|freez|kyc (update|expired)/i,20,'Threatens account block or KYC expiry'],[/lottery|prize|winner|reward|cashback|congratulations/i,20,'Promises prizes or rewards'],[/https?:\/\/|bit\.ly|tinyurl|\.xyz|\.top|\.click/i,15,'Contains a link'],[/anydesk|teamviewer|quicksupport|screen ?share/i,35,'Asks to install a remote-access app'],[/send money|collect request|scan (this )?qr/i,20,'Asks you to send money or scan a code'],[/customs|parcel|courier|arrest|police|cbi/i,25,'Impersonates an authority or courier']],POS='good great excellent happy love helpful easy fast smooth satisfied best thanks amazing friendly'.split(' '),NEG='bad poor slow angry hate worst difficult confusing fraud problem issue delay failed terrible disappointed complaint unhappy'.split(' ');
PG.tools=()=>CD('AI scam protection','<label>Paste an SMS, email or WhatsApp message</label><textarea id="sc_t" rows="4"></textarea><button class="btn" data-a="scam">Check message</button><div id="sc_o"></div>')+CD('Customer sentiment analysis','<label>Paste customer feedback</label><textarea id="se_t" rows="4"></textarea><button class="btn" data-a="sent">Analyze sentiment</button><div id="se_o"></div>');
A.scam=()=>{const t=S('#sc_t').trim();if(!t)return toast('Paste a message first','bad');const h=SC.filter(r=>r[0].test(t)),s=Math.min(100,h.reduce((a,r)=>a+r[1],0)),l=s>=60?'High':s>=30?'Medium':'Low';$('#sc_o').innerHTML=`<p><span class="tag ${l=='Low'?'ok':'bad'}">${l} scam risk · ${s}/100</span></p>${h.length?LI(h.map(r=>r[2])):'<p class="mu">No known scam patterns found.</p>'}<p class="disc">Never share OTP or PIN. Banks never ask for them. Rule-based check; not a guarantee.</p>`};
A.sent=()=>{const w=S('#se_t').toLowerCase().match(/[a-z']+/g)||[];let p=0,n=0;w.forEach((x,i)=>{const ng=/^(not|never|no|n't)$/.test(w[i-1]||'')||(w[i-1]||'').endsWith("n't"),ps=POS.includes(x),ne=NEG.includes(x);if(ps)ng?n++:p++;if(ne)ng?p++:n++});if(!p&&!n)return $('#se_o').innerHTML='<p class="mu">No sentiment words found. Add more text.</p>';const s=(p-n)/(p+n);$('#se_o').innerHTML=`<p><span class="tag ${s>.2?'ok':s<-.2?'bad':''}">${s>.2?'Positive':s<-.2?'Negative':'Neutral'} · ${s.toFixed(2)}</span></p><p class="mu">${p} positive and ${n} negative cues (lexicon-based).</p>`};
/* camera banking (computer vision) */
const vd=[[0,1,2,3,4,5,6,7,8,9],[1,2,3,4,0,6,7,8,9,5],[2,3,4,0,1,7,8,9,5,6],[3,4,0,1,2,8,9,5,6,7],[4,0,1,2,3,9,5,6,7,8],[5,9,8,7,6,0,4,3,2,1],[6,5,9,8,7,1,0,4,3,2],[7,6,5,9,8,2,1,0,4,3],[8,7,6,5,9,3,2,1,0,4],[9,8,7,6,5,4,3,2,1,0]],vp=[[0,1,2,3,4,5,6,7,8,9],[1,5,7,6,2,8,3,0,9,4],[5,8,0,3,7,9,6,1,4,2],[8,9,1,6,0,4,3,5,2,7],[9,4,5,3,1,2,6,8,7,0],[4,2,8,6,5,7,3,9,0,1],[2,7,9,3,8,0,6,4,1,5],[7,0,4,6,9,1,3,2,5,8]],verh=s=>{let c=0;[...s].reverse().forEach((ch,i)=>{c=vd[c][vp[i%8][+ch]]});return c==0};
const mask=(raw)=>{const s=raw.replace(/\s/g,'').toUpperCase();if(/^[A-Z]{5}\d{4}[A-Z]$/.test(s))return`PAN: XXXXX${s.slice(5,9)}X (format valid)`;if(/^\d{12}$/.test(s))return`Aadhaar: XXXX XXXX ${s.slice(-4)} (${verh(s)?'checksum valid':'checksum invalid'})`;return null};
PG.camera=()=>CD('Camera banking and document reader',`<p class="mu">Capture or upload a document photo. Image analysis runs in your browser. Images and full numbers are never stored; numbers are always masked.</p><video id="cv" playsinline muted style="display:none;width:100%;max-width:420px;border-radius:10px"></video><canvas id="cc" style="max-width:100%;border-radius:10px;margin-top:8px"></canvas><p><button class="btn" data-a="camStart">Start camera</button> <button class="btn g" data-a="camSnap">Capture</button> <input id="cf" type="file" accept="image/png,image/jpeg,image/webp" style="width:auto"></p><div id="co"><p class="mu">Waiting for an image.</p></div><label>Or type a PAN or Aadhaar number to validate and mask</label><div class="row" style="grid-template-columns:1fr auto"><input id="cn_i" autocomplete="off"><button class="btn" data-a="chk">Validate</button></div><div id="cm"></div><p class="disc">Use your own document or a sample. Do not upload other people's documents.</p>`);
A.camStart=async()=>{try{const s=await navigator.mediaDevices.getUserMedia({video:{facingMode:'environment'}}),v=$('#cv');v.srcObject=s;v.style.display='block';v.play()}catch(e){toast('Camera unavailable. Upload an image instead.','bad')}};
A.camSnap=()=>{const v=$('#cv');if(!v||!v.videoWidth)return toast('Start the camera first','bad');const c=$('#cc');c.width=v.videoWidth;c.height=v.videoHeight;c.getContext('2d').drawImage(v,0,0);cvRun()};
A.chk=()=>{const r=mask(S('#cn_i'));$('#cn_i').value='';$('#cm').innerHTML=r?`<p><span class="tag ok">Masked result</span> ${r}</p>`:'<p class="err">Enter a valid PAN (ABCDE1234F) or 12-digit Aadhaar number.</p>'};
document.addEventListener('change',e=>{if(e.target.id!='cf')return;const f=e.target.files[0];if(!f)return;if(!/^image\/(png|jpe?g|webp)$/.test(f.type)||f.size>5e6)return toast('Use a PNG, JPG or WebP under 5 MB','bad');const im=new Image();im.onload=()=>{const c=$('#cc'),s=Math.min(1,900/im.width);c.width=im.width*s;c.height=im.height*s;c.getContext('2d').drawImage(im,0,0,c.width,c.height);URL.revokeObjectURL(im.src);cvRun()};im.src=URL.createObjectURL(f)});
async function cvRun(){const c=$('#cc'),w=Math.min(320,c.width),h=Math.round(c.height*w/c.width),t=document.createElement('canvas');t.width=w;t.height=h;t.getContext('2d').drawImage(c,0,0,w,h);const d=t.getContext('2d').getImageData(0,0,w,h).data,g=new Float32Array(w*h);let br=0;for(let i=0;i<w*h;i++){g[i]=.299*d[i*4]+.587*d[i*4+1]+.114*d[i*4+2];br+=g[i]}br/=w*h;let lv=[],x0=w,x1=0,y0=h,y1=0,ed=0;for(let y=1;y<h-1;y++)for(let x=1;x<w-1;x++){const i=y*w+x,lp=4*g[i]-g[i-1]-g[i+1]-g[i-w]-g[i+w];lv.push(lp);const gx=g[i+1]-g[i-1],gy=g[i+w]-g[i-w];if(gx*gx+gy*gy>2500){ed++;x0=Math.min(x0,x);x1=Math.max(x1,x);y0=Math.min(y0,y);y1=Math.max(y1,y)}}const m=avg(lv),sh=avg(lv.map(v=>(v-m)**2)),cov=x1>x0?Math.round((x1-x0)*(y1-y0)/(w*h)*100):0,ok=br>60&&br<210&&sh>60&&cov>25;
$('#co').innerHTML=GR([kpi('Brightness',Math.round(br)+'/255',br<60?'Too dark':br>210?'Too bright':'Good'),kpi('Sharpness',Math.round(sh),sh>60?'Sharp':'Blurry'),kpi('Document area',cov+'%',cov>25?'Detected':'Move closer'),kpi('Edge density',(ed/(w*h)*100).toFixed(1)+'%')])+`<p><span class="tag ${ok?'ok':'bad'}">${ok?'Image quality suitable':'Retake the photo'}</span></p><p class="mu" id="ocr">Trying to read text...</p>`;try{if(!window.Tesseract){await new Promise((r,j)=>{const s=document.createElement('script');s.src='https://cdnjs.cloudflare.com/ajax/libs/tesseract.js/4.1.1/tesseract.min.js';s.onload=r;s.onerror=j;document.head.append(s)})}const r=await Promise.race([Tesseract.recognize(c,'eng'),new Promise((_,j)=>setTimeout(j,60000))]),tx_=r.data.text.toUpperCase(),pan=tx_.match(/[A-Z]{5}\d{4}[A-Z]/),aa=tx_.replace(/[^\d\s]/g,'').match(/\d{4}\s?\d{4}\s?\d{4}/),o=[pan&&mask(pan[0]),aa&&mask(aa[0])].filter(Boolean);$('#ocr').innerHTML=o.length?`<span class="tag ok">Auto-read</span> ${o.join(' · ')}<br><span class="mu">Verify against the document.</span>`:'No PAN or Aadhaar pattern found. Enter it manually below.'}catch(e){$('#ocr').textContent='Text reading is unavailable here (needs the OCR library). Enter the number manually below.'}}
/* advisors + report */
PG.advisors=u=>{const c=userC(u);if(!c.has)return empty;const ra=riskApp(c),eq={Conservative:30,Moderate:50,Aggressive:70}[ra.l],sur=Math.max(0,c.inc-c.out),cs=c.credit,pl_=prods(c),w=wellness(c),m=lin(ms(u).map(k=>+u.rec[k].sav)),n=ms(u).length;
return GR([kpi('Wellness index',w+'/100'),kpi('Risk appetite',ra.l)])+CD('AI portfolio advisor',`<p>Suggested mix for a ${ra.l.toLowerCase()} profile: <b>${eq}% equity</b>, <b>${90-eq}% debt</b>, <b>10% gold</b>.</p><p class="mu">Suggested monthly investment: ${R(Math.min(sur,c.inc*.15))} (15% of income, capped by your surplus).</p><p class="disc">Educational allocation, not investment advice.</p>`)+CD('AI credit score advisor',`<div class="row" id="crf">${FL('cr_s','Credit score',cs)}${FL('cr_u','Utilisation %',0)}${FL('cr_p','On-time payments %',100)}${FL('cr_i','Inquiries (12 months)',0)}</div><button class="btn" data-a="crd">Advise</button><div id="cr_o"></div>`)+CD('Hyper-personalized banking plan',LI([`Save ${R(Math.max(0,c.inc*.2-sur)+sur*0)} more a month to reach a 20% savings rate.`.replace(/^Save ₹0 more a month to reach a 20% savings rate\./,'Savings rate already at or above 20%.'),...pl_.map(p=>'Consider: '+p),`Priority: ${council(c).n}`]))+CD('Future customer prediction',n>=3?`<p>Savings are trending ${R(m.s)}/month. Estimated savings next month: <b>${R(Math.max(0,m.f(1)))}</b> (linear regression on ${n} months).</p>`:'<p class="mu">Add 3+ months to predict.</p>')+CD('Auto-generated banking report',`<button class="btn" data-a="pdf">Download PDF report</button><p class="disc">Uses the jsPDF library. Downloads may be blocked inside embedded previews; the downloaded project works normally.</p>`)};
A.crd=()=>{const s=V('#cr_s'),u=V('#cr_u'),p=V('#cr_p'),i=V('#cr_i'),t=[],g=(u>30?(t.push('Reduce utilisation below 30%'),15):0)+(p<100?(t.push('Pay every EMI on time'),20):0)+(i>3?(t.push('Avoid new credit inquiries'),8):0);t.push('Keep older accounts open','Check your credit report regularly');$('#cr_o').innerHTML=`<p>Current ${s||'not provided'}${s?` · potential simulated improvement <b>+${g}</b>`:''}</p>${LI(t)}<p class="disc">Estimate based on demo rules; not guaranteed.</p>`};
A.pdf=()=>{const J=window.jspdf&&window.jspdf.jsPDF;if(!J)return toast('PDF library not loaded (needs internet)','bad');const u=me(),c=userC(u),o=council(c),d=new J(),L=[`MANSHORA Banking Report`,`Customer: ${u.name} (${c.city})`,`Generated: ${new Date().toLocaleDateString('en-IN')}`,'',`Monthly income: ${R(c.inc)}`,`Monthly outgo: ${R(c.out)}`,`Savings rate: ${c.sr.toFixed(1)}%`,`Net worth: ${R(c.nw)}`,`Health score: ${c.score}/100 (${c.risk} risk)`,`Wellness index: ${wellness(c)}/100`,`Digital adoption: ${c.adopt?c.adopt+'/100':'not provided'}`,'',`Opportunity: ${o.o}`,`Risk: ${o.r}`,`Next action: ${o.n}`,'','Educational and simulated insights only; not financial advice.'];d.setFontSize(11);L.forEach((t,i)=>d.text(t,15,20+i*8));try{d.save('manshora-report.pdf');toast('Report generated')}catch(e){toast('Download was blocked here','bad')}};
/* executive */
PG.exec=()=>{const A_=ALLC();if(!A_.length)return empty;const n=A_.length,ad=A_.filter(c=>c.adopt),km_=A_.length>=3?km(A_.map(c=>[c.sr/100,c.adopt/100,c.dti/100,c.score/100]),3):null,sip=avg(A_.map(c=>propens(c)[0][1])),ins=avg(A_.map(c=>propens(c)[1][1])),inv=A_.reduce((a,c)=>a+Math.max(0,c.inc*.1-c.invM)*12,0),ig=A_.reduce((a,c)=>a+Math.max(0,c.inc*120-c.ins),0),bk=[0,1,2,3,4].map(i=>A_.filter(c=>c.score>=i*20&&c.score<(i?i*20+20:20)+(i==4?1:0)).length);
P3=[[{n:'Accounts',d:bk}],['0-20','20-40','40-60','60-80','80+']];
const segs=km_?[0,1,2].map(k=>({k,m:A_.filter((_,i)=>km_.L[i]==k),c:km_.C[k]})).filter(s=>s.m.length).sort((a,b)=>b.c[3]-a.c[3]):null;
return`<p class="card">${ad.length?`Average digital adoption is ${Math.round(avg(ad.map(c=>c.adopt)))}/100`:'Digital adoption data has not been entered yet'}, average health score is ${Math.round(avg(A_.map(c=>c.score)))}, and ${A_.filter(c=>c.invM<c.inc*.1).length} of ${n} customers invest under 10% of income, an opportunity area.</p>`+GR([kpi('Customers',n),kpi('Avg health score',Math.round(avg(A_.map(c=>c.score)))),kpi('Avg digital adoption',ad.length?Math.round(avg(ad.map(c=>c.adopt)))+'/100':'No data'),kpi('Total net worth',R(A_.reduce((a,c)=>a+c.nw,0))),kpi('SIP adoption prediction',pc(sip)+'%','avg propensity'),kpi('Insurance conversion prediction',pc(ins)+'%','avg propensity'),kpi('Revenue opportunity',R(inv*.01+ig*.0015)+'/yr','assumes 1% fee on new SIP flow and 0.15% premium on cover gap'),kpi('High-risk customers',A_.filter(c=>c.risk=='High').length)])+CD('Customer analytics: health score distribution (3D)','<div id="d3" class="c3d"></div>')+CD('Customer segmentation (k-means clustering)',segs?TB(['Cluster','Customers','Avg income','Avg health'],segs.map((s,i)=>[['Strong','Middle','Needs support'][i],s.m.length,R(avg(s.m.map(c=>c.inc))),Math.round(s.c[3]*100)])):'<p class="mu">Needs 3+ registered accounts.</p>')+CD('Banking performance overview',TB(['Metric','Value'],[['Loan holders',pc(A_.filter(c=>c.emi>0).length/n)+'%'],['Investors',pc(A_.filter(c=>c.invT>0).length/n)+'%'],['Avg savings rate',avg(A_.map(c=>c.sr)).toFixed(1)+'%'],['Avg DTI',avg(A_.map(c=>c.dti)).toFixed(1)+'%']]))+NOTE+`<p class="disc">${DISC}</p>`};
