let P3=null,t3=0;Object.keys(users).forEach(k=>{if(users[k].demo)delete users[k]});save();
const art=k=>{k=(k||0)%6;const c=COL[k%4],d=COL[(k+1)%4],H=[18,30,24,42,36,54,48],P=[[15,65],[55,50],[90,58],[130,30],[170,22]],N=[[40,25],[100,60],[160,28],[70,70],[130,20]],
M=[H.map((h,i)=>`<rect x="${22+i*24}" y="${70-h}" width="14" height="${h}" rx="2" fill="${i%2?d:c}"/>`).join(''),
`<polyline points="${P.map(p=>p.join(',')).join(' ')}" fill="none" stroke="${c}" stroke-width="3"/>${P.map(p=>`<circle cx="${p[0]}" cy="${p[1]}" r="5" fill="${d}"/>`).join('')}`,
`<circle cx="100" cy="45" r="28" fill="none" stroke="#1b2842" stroke-width="12"/><circle cx="100" cy="45" r="28" fill="none" stroke="${c}" stroke-width="12" stroke-dasharray="110 66" transform="rotate(-90 100 45)"/><circle cx="100" cy="45" r="28" fill="none" stroke="${d}" stroke-width="12" stroke-dasharray="40 136" stroke-dashoffset="-110" transform="rotate(-90 100 45)"/>`,
N.map((p,i)=>`<line x1="${p[0]}" y1="${p[1]}" x2="${N[(i+2)%5][0]}" y2="${N[(i+2)%5][1]}" stroke="#2a3a5c"/>`).join('')+N.map(p=>`<circle cx="${p[0]}" cy="${p[1]}" r="7" fill="${c}"/>`).join(''),
`<path d="M100 12 L145 28 V50 C145 68 120 78 100 84 C80 78 55 68 55 50 V28 Z" fill="${c}" fill-opacity=".2" stroke="${c}" stroke-width="3"/><path d="M82 46 l14 14 l24 -26" fill="none" stroke="${d}" stroke-width="5"/>`,
[0,1,2].map(i=>`<ellipse cx="100" cy="${64-i*16}" rx="38" ry="11" fill="${i%2?d:c}" fill-opacity=".85" stroke="#0f1a30"/>`).join('')];
return`<svg class="art" viewBox="0 0 200 90" preserveAspectRatio="xMidYMid meet" role="img" aria-label="Illustration"><rect width="200" height="90" fill="#0f1a30"/><circle cx="175" cy="10" r="40" fill="${c}" fill-opacity=".08"/>${M[k]}</svg>`};
const banner=k=>{k=(k||0)%4;const c=COL[k%4],d=COL[(k+1)%4],n=40,B=[...Array(n).keys()].map(i=>{const h=14+((i*37+k*11)%23)+i*.9;return`<rect x="${i*40+8}" y="${80-h}" width="24" height="${h}" rx="3" fill="${i%3?c:d}" fill-opacity="${(.25+i/n*.5).toFixed(2)}"/>`}).join(''),pts=[...Array(n).keys()].map(i=>`${i*40+20},${58-i*.9-((i*53+k*7)%11)}`).join(' ');return`<svg class="art" viewBox="0 0 1600 80" preserveAspectRatio="xMidYMid slice" role="img" aria-label="Decorative financial chart"><rect width="1600" height="80" fill="#0f1a30"/>${B}<polyline points="${pts}" fill="none" stroke="${d}" stroke-width="2.5"/></svg>`};
function hero3d(){const el=$('#h3d');if(el){el.dataset.deco=1;bars3d(el,[{n:'Revenue',d:[3,4,3.5,5,6,5.5,7,8,7.5,9,10,11]},{n:'Savings',d:[1,1.5,2,2,3,3.2,4,4.5,5,6,6.5,8]}],MN)}}
function bars3d(el,ser,lab){if(!el)return;if(!window.THREE){el.innerHTML='<p class="mu">The 3D view needs an internet connection to load its library.</p>';return}
try{const h=+el.dataset.h||260;let w=el.clientWidth||400;el.innerHTML='';const sc=new THREE.Scene(),cam=new THREE.PerspectiveCamera(42,w/h,.1,100),rd=new THREE.WebGLRenderer({antialias:true,alpha:true}),g=new THREE.Group(),n=lab.length,mx=Math.max(...ser.flatMap(s=>s.d),1),C=[0x3b82f6,0x22d3ee,0x34d399,0xfbbf24],lb=document.createElement('div'),bars=[];
lb.className='lbl3';rd.setPixelRatio(Math.min(devicePixelRatio||1,2));rd.setSize(w,h);el.append(rd.domElement,lb);cam.position.set(0,5.5,n*.62+5);cam.lookAt(0,1.6,0);
sc.add(new THREE.AmbientLight(0xffffff,.65));const dl=new THREE.DirectionalLight(0xffffff,.85);dl.position.set(4,9,6);sc.add(dl);g.add(new THREE.GridHelper(n+2,n+2,0x22d3ee,0x1b2842));sc.add(g);
ser.forEach((s,j)=>s.d.forEach((v,i)=>{const hh=Math.max(.06,v/mx*5),m=new THREE.Mesh(new THREE.BoxGeometry(.55,hh,.55),new THREE.MeshStandardMaterial({color:C[j%4],metalness:.25,roughness:.45}));m.position.set((i-(n-1)/2)*.95,0,(j-(ser.length-1)/2)*.8);m.scale.y=.01;m.userData={hh,t:lab[i]+' · '+s.n+': '+Math.round(v).toLocaleString('en-IN')};g.add(m);bars.push(m)}));
let dr=0,px=0,py=0,ry=.5;const ray=new THREE.Raycaster(),mv=new THREE.Vector2(),cv=rd.domElement,rm=matchMedia('(prefers-reduced-motion:reduce)').matches;
cv.onpointerdown=e=>{dr=1;px=e.clientX;py=e.clientY};addEventListener('pointerup',()=>dr=0);
cv.onpointermove=e=>{if(dr){ry+=(e.clientX-px)*.01;g.rotation.x=cl(g.rotation.x+(e.clientY-py)*.005,-.3,.6);px=e.clientX;py=e.clientY}const b=cv.getBoundingClientRect();mv.set((e.clientX-b.left)/b.width*2-1,-(e.clientY-b.top)/b.height*2+1);ray.setFromCamera(mv,cam);const hit=ray.intersectObjects(bars)[0];lb.textContent=hit&&!el.dataset.deco?hit.object.userData.t:''};
(function loop(){if(!document.body.contains(cv)){rd.dispose();rd.forceContextLoss&&rd.forceContextLoss();return}
if(el.clientWidth&&el.clientWidth!==w){w=el.clientWidth;rd.setSize(w,h);cam.aspect=w/h;cam.updateProjectionMatrix()}
if(!dr&&!rm)ry+=.004;g.rotation.y=ry;bars.forEach(m=>{m.scale.y+=(1-m.scale.y)*(rm?1:.06);m.position.y=m.userData.hh*m.scale.y/2});rd.render(sc,cam);requestAnimationFrame(loop)})()}catch(e){el.innerHTML='<p class="mu">3D view is not supported in this browser.</p>'}}
document.addEventListener('pointermove',e=>{const t=e.target.closest&&e.target.closest('.card.h');if(!t||e.pointerType=='touch'||matchMedia('(prefers-reduced-motion:reduce)').matches)return;const r=t.getBoundingClientRect(),x=(e.clientX-r.left)/r.width-.5,y=(e.clientY-r.top)/r.height-.5;t.style.transform=`perspective(700px) rotateX(${-y*9}deg) rotateY(${x*9}deg)`});
document.addEventListener('pointerout',e=>{const t=e.target.closest&&e.target.closest('.card.h');if(t&&!t.contains(e.relatedTarget))t.style.transform=''});
